### ISSUE TITLE
Grafana target pod name error

### ISSUE THREAD

**Issue by joneal** [wuestkamp/k8s-example-resource-monitoring#1]
Brand new to K8S/Prometheus/Grafana, so I may be off base.   Trying to duplicate this system locally.  It appears that the Grafana target name for "container_cpu_usage_seconds_total" is incorrect.

The pod selector for that metric is "pod_name" while the other three to just "pod'.  I could not get CPU usage to display in Grafana until I also changed its selector to just "pod".

"targets": [
        {
          "expr": "rate(container_cpu_usage_seconds_total{pod_name ******** <-- THIS SHOULD BE "pod" ********=~\"compute-.*\", image!=\"\", container!=\"POD\"}[5m])",
          "hide": false,
          "legendFormat": "container usage",
          "refId": "A"
        },
        {
          "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"compute-.*\"})",
          "hide": false,
          "legendFormat": "container requests",
          "refId": "B"
        },
        {
          "expr": "avg(kube_pod_container_resource_limits_cpu_cores{pod=~\"compute-.*\"})",
          "hide": false,
          "legendFormat": "container limits",
          "refId": "C"
        },
        {
          "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"compute-.*\", container!=\"POD\", image!=\"\"}[5m])",
          "hide": false,
          "legendFormat": "throttling",
          "refId": "D"
        }
      ]

**Comment by wuestkamp** [comment]
Hi @joneal thanks for updating here! It seems that metrics have been changed from Kubernetes version 1.16 on: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#removed-metrics

I updated the Readme and the Medium article according. Which version did you use locally?

**Comment by joneal** [comment]
For K8S, I believe I saw this in v1.17.2.  (I've since upgraded to v1.17.4).

**Comment by wuestkamp** [comment]
Ok then this has been updated in this repo and medium article! :)
